#!/usr/bin/env python3
"""Embed the checkout's commit ID, keeping the version reply within ATT MTU 23."""
from pathlib import Path
import subprocess

ROOT = Path(__file__).resolve().parents[1]

if __name__ == '__main__':
    sha = subprocess.check_output(
        ['git', 'rev-parse', 'HEAD'], cwd=ROOT, text=True
    ).strip()[:12]
    header = ROOT / 'apps/opendisplay/src/build_version.h'
    content = f'/* Generated by tools/generate_version.py. */\n#define OD_BUILD_SHA "{sha}"\n'
    if not header.exists() or header.read_text() != content:
        header.write_text(content)
