#!/usr/bin/env python3
"""Generate the immutable OpenDisplay record from the application's GPIO config."""
from pathlib import Path
import binascii
import re

ROOT = Path(__file__).resolve().parents[1]

def config_bytes():
    settings = (ROOT / 'apps/opendisplay/syscfg.yml').read_text()
    pins = {key: int(value) for key, value in re.findall(r'    EPD_(\w+):\n        value: (\d+)', settings)}
    system = bytearray(22)
    system[2] = 1  # BLE
    system[4:7] = b"\xff\xff\xff"  # No controllable power pins
    manufacturer = bytearray(22)  # IDs unknown: do not claim an assigned ID
    power = bytearray(30)
    power[8:10] = b'\xff\xff'  # No battery sense GPIO configured
    panel = bytearray(46)
    panel[1] = 1  # e-paper
    panel[4:8] = bytes([104, 0, 212, 0])
    panel[15:25] = bytes([pins['RESET'], pins['BUSY'], pins['DC'], pins['CS'],
                         pins['MOSI'], 1, 0, 25, pins['SCK'], 255])
    body = bytearray([0, 0, 1])
    for kind, record in [(1, system), (2, manufacturer), (4, power), (0x20, panel)]:
        body += bytes([0, kind]) + record
    crc = binascii.crc_hqx(body, 0xffff)
    return body + crc.to_bytes(2, 'little')

def render():
    data = config_bytes()
    return ('/* Generated by tools/generate_config.py; OpenDisplay config v1.\n'
            ' * MCU/panel/manufacturer IDs unknown (0); board config is immutable. */\n'
            'static const unsigned char od_config[] = {\n' +
            ''.join('    ' + ', '.join(f'0x{x:02x}' for x in data[i:i+12]) + ',\n'
                    for i in range(0, len(data), 12)) + '};\n')

if __name__ == '__main__':
    (ROOT / 'apps/opendisplay/src/config_data.h').write_text(render())
